version: "3.9"
services:

  autosearch:
    container_name: ${USER_NAME}-autosearch
    hostname: autosearch
    image: hungnguyen991995/autosearch:latest
    privileged: true
    restart: always
    networks:
          - web_net
    environment:
      - REMOTE_DRIVER_URL=http://browser:4444/wd/hub
      - SEARCH_INTERVAL=${SEARCH_INTERVAL} 
      - SLEEP_INTERVAL_FROM=${SLEEP_INTERVAL_FROM} 
      - SLEEP_INTERVAL_TO=${SLEEP_INTERVAL_TO}   
      - WARM_UP_SLEEP=${WARM_UP_SLEEP}   
    depends_on:
      - browser
    volumes:
       - ./config/${USER_NAME}/AppSetting.json:/app/AppSetting.json:rw
       - ./config/${USER_NAME}/SavedTitles.txt:/app/SavedTitles.txt:rw

  browser:
    container_name: ${USER_NAME}-browser
    image: selenium/standalone-edge:111.0
    hostname: browser
    shm_size: 2gb
    privileged: true
    restart: always
    networks:
          - web_net
    environment:
      - SE_SCREEN_WIDTH=1920
      - SE_SCREEN_HEIGHT=1080
      - SE_NODE_SESSION_TIMEOUT=${SE_NODE_SESSION_TIMEOUT}
      - SE_DRAIN_AFTER_SESSION_COUNT=${SE_DRAIN_AFTER_SESSION_COUNT}
      - SE_NODE_OVERRIDE_MAX_SESSIONS=${SE_NODE_OVERRIDE_MAX_SESSIONS}
      - SE_NODE_MAX_SESSIONS=${SE_NODE_MAX_SESSIONS}
    ports:
      - "${BROWSER_PORT}:4444"
      - "${BROWSER_VIEW_PORT}:7900"
    deploy:
        resources:
            limits:
              cpus: "1"
              memory: 900M
            reservations:
              cpus: "1"
              memory: 800M

networks:
    web_net:
      external: false
      driver:  bridge