version: "3.9"
services:
  executor-0:
    container_name: executor-0
    image: hungnguyen991995/supper-search
    shm_size: 2gb
    restart: always
    privileged: true
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SLEEP_INTERVAL_FROM=${SLEEP_INTERVAL_FROM}
      - SLEEP_INTERVAL_TO=${SLEEP_INTERVAL_TO}

  executor-1:
    container_name: executor-1
    image: hungnguyen991995/supper-search
    shm_size: 2gb
    restart: always
    privileged: true
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SLEEP_INTERVAL_FROM=${SLEEP_INTERVAL_FROM}
      - SLEEP_INTERVAL_TO=${SLEEP_INTERVAL_TO}


  executor-2:
    container_name: executor-2
    image: hungnguyen991995/supper-search
    shm_size: 2gb
    restart: always
    privileged: true
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SLEEP_INTERVAL_FROM=${SLEEP_INTERVAL_FROM}
      - SLEEP_INTERVAL_TO=${SLEEP_INTERVAL_TO}