version: "3.9"
services:
  database:
    image: postgres:16.1-alpine
    container_name: database
    ports:
      - '5432:5432'
    networks:
          - web_net
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    # volumes: 
      # - db1:/var/lib/postgresql/data
  
  executor-0:
    container_name: executor-0
    image: hungnguyen991995/supper-search
    shm_size: 2gb
    restart: always
    privileged: true
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SLEEP_INTERVAL_FROM=${SLEEP_INTERVAL_FROM}
      - SLEEP_INTERVAL_TO=${SLEEP_INTERVAL_TO}
    depends_on:
      - database
    networks:
      - web_net

  # autosearch:
  #   container_name: autosearch
  #   hostname: autosearch
  #   image: hungnguyen991995/autosearch:latest
  #   privileged: true
  #   restart: always
  #   networks:
  #         - web_net
  #   environment:
  #     - REMOTE_DRIVER_URL=http://browser:4444/wd/hub
  #     - SEARCH_INTERVAL=60
  #     - SLEEP_INTERVAL_FROM=${SLEEP_INTERVAL_FROM} 
  #     - SLEEP_INTERVAL_TO=${SLEEP_INTERVAL_TO}   
  #     - WARM_UP_SLEEP=60 
  #     - CONNECTION_STRING=User ID=postgres;Password=postgres;Host=database;Port=5432;Database=postgres; 
  #   depends_on:
  #     - browser
    
  # browser:
  #   container_name: browser
  #   image: selenium/standalone-edge:111.0
  #   hostname: browser
  #   shm_size: 2gb
  #   privileged: true
  #   restart: always
  #   networks:
  #         - web_net
  #   environment:
  #     - SE_SCREEN_WIDTH=1920
  #     - SE_SCREEN_HEIGHT=1080
  #     - SE_NODE_SESSION_TIMEOUT=600
  #     - SE_DRAIN_AFTER_SESSION_COUNT=0
  #     - SE_NODE_OVERRIDE_MAX_SESSIONS=true
  #     - SE_NODE_MAX_SESSIONS=5
  #   ports:
  #     - "4444:4444"
  #     - "7900:7900"

networks:
    web_net:
      external: false
      driver:  bridge

volumes:
  db1: