version: "3.9"
services:
  database:
    image: postgres:14.1-alpine
    container_name: database
    restart: always
    ports:
      - '5432:5432'
    networks:
          - web_net
    environment:
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes: 
      - db:/var/lib/postgresql/data
  
  executor-0:
    container_name: executor-0
    image: hungnguyen991995/supper-search
    shm_size: 2gb
    restart: always
    privileged: true
    environment:
      - CONNECTION_STRING=${CONNECTION_STRING}
      - SLEEP_INTERVAL_FROM=${SLEEP_INTERVAL_FROM}
      - SLEEP_INTERVAL_TO=${SLEEP_INTERVAL_TO}
    depends_on:
      - database
    
networks:
    web_net:
      external: false
      driver:  bridge

volumes:
  db: